[package]
name = "cineco_cal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
ics = "0.5"
regex = "1"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "cookies", "form"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.27"
uuid = { version = "1", features = ["v5"] }
axum = "0.8"
tower-http = { version = "0.7", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = { version = "0.15" }